### ISSUE TITLE
No Suitable driver found Exception while connecting to DB2

### ISSUE THREAD

**Issue by darshanmehta10** [baztian/jaydebeapi#110]
Versions:
JPype1 : 0.6.3
JayDeBeApi : 1.1.1
Java : OpenJDK 8

Driver jar : https://artifacts.alfresco.com/nexus/content/repositories/public/com/ibm/db2/jcc/db2jcc4/10.1/db2jcc4-10.1.jar

Following is the code:

```
import sys
import jaydebeapi
import jpype

if jpype.isJVMStarted() and not jpype.isThreadAttachedToJVM():
    jpype.attachThreadToJVM()
    jpype.java.lang.Thread.currentThread().setContextClassLoader(jpype.java.lang.ClassLoader.getSystemClassLoader())

connection = jaydebeapi.connect(
    'com.ibm.db2.jcc.DB2Driver',
    <url>,
    {'user': <user>, 'password': <password>, 'charset': 'UTF8'},
     '/usr/lib/db2jcc.jar')

cursor=connection.cursor()

cursor.execute(<some_sql>)
```

This returns the following Exception:

```
Traceback (most recent call last):
  File "/scripts/execute.py", line 13, in <module>
    '/usr/lib/db2jcc.jar')
  File "/usr/local/lib/python3.6/site-packages/jaydebeapi/__init__.py", line 380, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "/usr/local/lib/python3.6/site-packages/jaydebeapi/__init__.py", line 199, in _jdbc_connect_jpype
    return jpype.java.sql.DriverManager.getConnection(url, *dargs)
jpype._jexception.SQLExceptionPyRaisable: java.sql.SQLException: No suitable driver found for /scripts/execute.py
```

As the code shows, I have already tried the workaround mentioned [here](https://stackoverflow.com/a/52703195/1120793) but that doesn't seem to have worked.

**Comment by kimehta** [comment]
http://www-01.ibm.com/support/docview.wss?uid=swg21363866

https://www.ibm.com/support/knowledgecenter/SSQNUZ_1.1.0/com.ibm.icpdata.doc/dsx/createconnectionsdirect.html?view=kc#createconnectionsdirect__pyexampleluwcloud

https://www.ibm.com/support/knowledgecenter/SSQNUZ_1.1.0/com.ibm.icpdata.doc/dsx/createconnectionsdirect.html?view=kc#createconnectionsdirect__pyexampleother

**Comment by diman82** [comment]
Facing the same issue, but only when running code directly (calling main.py), running a Jupyter notebook works well (there is no such error).

What can be the problem? Why it's running in a Jupyter notebook, but fails to run directly within code?

**Comment by imavo** [comment]
Getting the same symptom, with jaydebeapi=1.2.3 and jpype=1.4.1 and python 3.8.5 and python 3.11.2.
The supposed workaround as mentioned above and in #114 does not help.
I verified the underlying jre (jdk-20) can successfully connect to the remote Db2 database, so I know that the CLASSPATH, JAVA_HOME, PATH, the url are all valid. 
But jaydebeapi.connect() throws **java.sql.SQLException: No suitable driver found for jdbc:/db2://192.168.1.78:50022/mydb.**

It makes no difference whether I specify a final argument of the fully-qualified pathname to db2jcc4.jar to jaydebeapi.connect().

Any suggestions?
