### ISSUE TITLE
python2.7 install failed

### ISSUE THREAD

**Issue by chenshanghao** [baztian/jaydebeapi#152]
Installed the package failed with the following message.

```
 $ pip install JayDeBeApi
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting JayDeBeApi
  Using cached https://files.pythonhosted.org/packages/61/bd/bc98713b64ad6f7da1c9f3a6b43e3433a653c0fdb1346a0d0e228ba17315/JayDeBeApi-1.2.2-py2-none-any.whl
Collecting JPype1
  Using cached https://files.pythonhosted.org/packages/62/8e/5e9070084e2722e214ded0464c1b41573b9c7328c7bee4d87796e3f84880/JPype1-0.7.5.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ZMihzb/JPype1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ZMihzb/JPype1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ZMihzb/JPype1/pip-egg-info
         cwd: /tmp/pip-install-ZMihzb/JPype1/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ZMihzb/JPype1/setup.py", line 4, in <module>
        import setupext
      File "setupext/__init__.py", line 4, in <module>
        from . import build_ext
      File "setupext/build_ext.py", line 100
        print("LIB = %s" % library, file=fd)
                                        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by baztian** [comment]
This should be fixed once https://pypi.org/project/JayDeBeApi/ version 1.2.3 has been uploaded. If everything works out as expected this should happen in about 10 minutes.
You probably have to uninstall JPype with `pip uninstall JPype1`.
The reason is that recent JPype versions are not compatible with Python 2 anymore. https://github.com/jpype-project/jpype/issues/754#issuecomment-633628203
Jaydebeapi 1.2.3 takes care of this and has changed dependencies for Python 2 versions.

**Comment by baztian** [comment]
https://pypi.org/project/JayDeBeApi/1.2.3/
