### ISSUE TITLE
Unable to load DLL [C:\Program Files\Java\jre1.8.0_131\bin\server\jvm.dll], error = The specified module could not be found.  at native\common\include\jp_platform_win32.h:58

### ISSUE THREAD

**Issue by drno-reg** [baztian/jaydebeapi#38]
Hello,

today on fresh Windows 2012 R2 Standart I installed JVM 8u131 x64 и x86 + python-3.6.1-amd64. I have script by Python for connect to Oracle by JDBC.

```
import jaydebeapi
import jpype

conn = jaydebeapi.connect("oracle.jdbc.driver.OracleDriver",
                          "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=host01)(PORT=1111)))(CONNECT_DATA=(SERVICE_NAME=oracle1)))",
                          ["user", "password"],
                          "c:\\Server\\Tomcat\\webapps\\um\\WEB-INF\\lib\\ojdbc7.jar",)
curs = conn.cursor()
curs.execute("select sysdate from dual")
results = curs.fetchall()
if results:
    for r in results:
        print (r)
curs.close()
conn.close()
```

on other windows 2012 R2 Standart(Windows 10) this sript working whithout errors. BUT on this installation Windows returned error

```
Traceback (most recent call last):
  File "C:/Server/repositories/projects/um/templates/Test/Test.py", line 39, in <module>
    "c:\\Server\\Tomcat\\webapps\\um\\WEB-INF\\lib\\ojdbc7.jar",)
  File "C:\Python36\lib\site-packages\jaydebeapi\__init__.py", line 381, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "C:\Python36\lib\site-packages\jaydebeapi\__init__.py", line 176, in _jdbc_connect_jpype
    jpype.startJVM(jvm_path, *args)
  File "C:\Python36\lib\site-packages\jpype\_core.py", line 50, in startJVM
    _jpype.startup(jvm, tuple(args), True)
RuntimeError: Unable to load DLL [C:\Program Files\Java\jre1.8.0_131\bin\server\jvm.dll], error = The specified module could not be found.
 at native\common\include\jp_platform_win32.h:58
```

How solve this problem?

p.s.
add special check file in folder

```
from os import listdir
jHome_dir='C:\\Program Files\\Java\\jre1.8.0_131\\bin\\server\\'
print(listdir (jHome_dir))
```

returned
['classes.jsa', 'jvm.dll', 'Xusage.txt']

What else I can to do?

**Comment by baztian** [comment]
You could try to set your JAVA_HOME environment variable appropriately.
