### ISSUE TITLE
How do I connect to a Netcool / Omnibus “Object Server” using JayDeBeApi module along with SAP Sybase JDBC drivers (jconn4.jar) in Python3?

### ISSUE THREAD

**Issue by mounikakuchana** [baztian/jaydebeapi#41]
hello,
I am new to python programming. I'm trying to connect to a Netcool Object Server using Python3, I am using JayDeBeApi module along with SAP Sybase JDBC drivers (jconn4.jar)

following is the sample script `

import jaydebeapi server="xxx" 
database="xx"
 user="xx" 
password="xx"
jclassname='com.sybase.jdbc4.jdbc.SybDriver'
url='jdbc:sybase:Tds://'+server+'/'+database
driver_args=[url,user,password]
jars="path/jconn4.jar"
conn=jaydebeapi.connect(jclassname,driver_args,jars)
curs = conn.cursor()
curs.execute("select * from status")
curs.fetchall()`

when I am executing the script it showing an error as follows

"/usr/local/lib/python3.5/site-packages/jaydebeapi/init.py", line 381, in connect jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs) File "/usr/local/lib/python3.5/site-packages/jaydebeapi/init.py", line 199, in _jdbc_connect_jpype return jpype.java.sql.DriverManager.getConnection(url, *dargs) 
RuntimeError: No matching overloads found. at native/common/jp_method.cpp:117

if anyone successfully connected to a Netcool Object Server using JayDeBeApi module in Python3? please share the sample script

thanks

**Comment by yangLambkin** [comment]
I use python 2 to connect DB2 , also meet the same problem: RuntimeError: No matching overloads found. at native/common/jp_method.cpp:117.
Detailed Error;
Traceback (most recent call last):
  File "dbConn.py", line 6, in <module>
    jaydebeapi.connect('com.ibm.db2.jcc.DB2Driver', connection_string,'/opt/webService/ibm/db2jcc.jar')
  File "/usr/local/lib/python2.7/dist-packages/jaydebeapi/__init__.py", line 381, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "/usr/local/lib/python2.7/dist-packages/jaydebeapi/__init__.py", line 199, in _jdbc_connect_jpype
    return jpype.java.sql.DriverManager.getConnection(url, *dargs)
RuntimeError: No matching overloads found. at native/common/jp_method.cpp:117

**Comment by Mawster** [comment]
Hi guyz - do you use the connect method right ?

I tried @mounikakuchana code and that can not work because the connect api definition is not like you used it (at least in version JayDeBeApi-1.1.1) - use it this way (example for Informix connection):

`jclassname = 'com.informix.jdbc.IfxDriver'
 url = 'jdbc:informix-sqli://<hostname>:<port>:INFORMIXSERVER=<server>'
    driver_args = ['<user>', '<password>']
    jars = glob.glob("<folder containing your driver jars>")
    conn = jaydebeapi.connect(jclassname=jclassname,url=url, driver_args=driver_args, jars=jars)`
