### ISSUE TITLE
Error java.sql.SQLExceptionPyRaisable: java.sql.SQLException: No suitable driver found

### ISSUE THREAD

**Issue by alexisrolland** [baztian/jaydebeapi#66]
Hello,
I have the following function to connect to a *Teradata* database:

```python
def fGetJDBCConnexion():
        oCipherKey = fGetParameter(pFileName='global_parameter.ini', pSectionName='AUDIT', pParameterName='oCipherKey').encode("UTF-8")
        oCipher = Fernet(oCipherKey)
        oPasswordEncrypted = fGetParameter(pFileName='global_parameter.ini', pSectionName='AUDIT', pParameterName='oPassword').encode("UTF-8")
        oPassword = oCipher.decrypt(oPasswordEncrypted).decode("UTF-8")

        # Retrieve audit database name and connexion string from global parameter file
        oDataBase = fGetParameter(pFileName='global_parameter.ini', pSectionName='AUDIT', pParameterName='oDataBase')
        oUserName = fGetParameter(pFileName='global_parameter.ini', pSectionName='AUDIT', pParameterName='oUserName')
        oConnexionString = fGetParameter(pFileName='global_parameter.ini', pSectionName='AUDIT', pParameterName='oConnexionStringJDBC')

        # Connect
        oConnexion = jaydebeapi.connect(
            'com.teradata.jdbc.TeraDriver',
            oConnexionString,
            {'user': oUserName, 'password': oPassword, 'tmode': 'TERA', 'charset': 'UTF8'},
            os.path.dirname(__file__) + '/teradataDriverJdbc.jar')
        return(oConnexion, oDataBase)
```

This function works well when doing unit tests. It returns both the connection object and my database name as expected.

However, this function is called as part of a bigger Flask API built with Flask-Restplus, and the function returns the following error message when it's executed in that context:

```
--------------------------------------------------------------------------------
ERROR in app [/home/alexis/dq/lib/python3.5/site-packages/flask/app.py:1587]:
Exception on /dataqualityframework/api/v1/batchowners [GET]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alexis/dq/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexis/dq/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alexis/dq/lib/python3.5/site-packages/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alexis/dq/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alexis/dq/lib/python3.5/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "api.py", line 152, in get
    oStatus, oBatchOwners = batch_owner.fGetBatchOwner()
  File "/home/alexis/data-quality/api/batch_owner.py", line 125, in fGetBatchOwner
    oData = fGetBatchOwnerData()
  File "/home/alexis/data-quality/api/batch_owner.py", line 107, in fGetBatchOwnerData
    oConnexion, oQueryParameter['DATABASE'] = global_function_api.fGetJDBCConnexion()
  File "/home/alexis/data-quality/api/global_function_api.py", line 133, in fGetJDBCConnexion
    os.path.dirname(__file__) + '/teradataDriverJdbc.jar')
  File "/home/alexis/dq/lib/python3.5/site-packages/jaydebeapi/__init__.py", line 381, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "/home/alexis/dq/lib/python3.5/site-packages/jaydebeapi/__init__.py", line 199, in _jdbc_connect_jpype
    return jpype.java.sql.DriverManager.getConnection(url, *dargs)
jpype._jexception.java.sql.SQLExceptionPyRaisable: java.sql.SQLException: No suitable driver found for jdbc:teradata://server-name.company.org
```

Would you please have any idea why and how to solve this issue?
Thanks

**Comment by alexisrolland** [comment]
I have tried this workardound:

```
import jpype
if not jpype.isThreadAttachedToJVM():
        jpype.attachThreadToJVM()
```

As described in: https://github.com/baztian/jaydebeapi/issues/14
But unfortunately it triggers a segmentation fault error.

**Comment by alexisrolland** [comment]
I have also created a question on Stackoverflow: https://stackoverflow.com/questions/49105504/jaydebeapi-triggers-java-sql-sqlexception-no-suitable-driver-found

**Comment by baztian** [comment]
Closed as already addressed at stackoverflow
