### ISSUE TITLE
Unable to install JayDeBeApi on Windows 10

### ISSUE THREAD

**Issue by krlng** [baztian/jaydebeapi#72]
I'm trying to install JayDeBeApi using pip on Window 10 and receive this error:

```
Building wheels for collected packages: JPype1
  Running setup.py bdist_wheel for JPype1 ... error
  Failed building wheel for JPype1
  Running setup.py clean for JPype1
Failed to build JPype1
Installing collected packages: JPype1, JayDeBeApi
  Running setup.py install for JPype1 ... error
Exception:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 82: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\programdata\anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\programdata\anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\programdata\anaconda3\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\programdata\anaconda3\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\programdata\anaconda3\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 82: invalid start byte
Cache entry deserialization failed, entry ignored
```

**Comment by krlng** [comment]
Sorry, did not really check, obviously a problem of JPype, not jaydebeapi's
