### ISSUE TITLE
No matching overloads found for getConnection

### ISSUE THREAD

**Issue by ghost** [baztian/jaydebeapi#74]
Hi I am trying to connect to my Hive Database using JayDeBeApi and I am getting below error:

`Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib/python3.6/site-packages/jaydebeapi/__init_.py", line 381, in connect
    jconn = jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "/usr/lib/python3.6/site-packages/jaydebeapi/__init_.py", line 199, in jdbc_connect_jpype
    return jpype.java.sql.DriverManager.getConnection(url, *dargs)
RuntimeError: No matching overloads found for getConnection in find. at native/common/jp_method.cpp:127`

Below is my code snippet that i am using:

`import jaydebeapi`
`conn_hive = jaydebeapi.connect('org.apache.hive.jdbc.HiveDriver',
        ['jdbc:hive2://localhost:10000/default;',
        'hive', 'hive'], '/usr/hdp/2.6.4.0-91/hive/lib/hive-jdbc-1.2.1000.2.6.4.0-91.jar',)`

**Comment by shubzumt** [comment]
I am using latest version of JayDeBeApi

**Comment by akbo** [comment]
The connect function has the following interface:
`connect(jclassname, url, driver_args=None, jars=None, libs=None)`

Try this:
`conn_hive = jaydebeapi.connect('org.apache.hive.jdbc.HiveDriver', 'jdbc:hive2://localhost:10000/default;', ['hive', 'hive'], '/usr/hdp/2.6.4.0-91/hive/lib/hive-jdbc-1.2.1000.2.6.4.0-91.jar')`

**Comment by gaodianzhuo** [comment]
worked,thanks,@akbo
