### ISSUE TITLE
jaydebeapi usable with twisted.enterprise.adbapi ?

### ISSUE THREAD

**Issue by zensaiello** [baztian/jaydebeapi#78]
To achieve nonBlocking Database calls, I was trying to see if jaydebeapi would work under twisted.enterprise.adbapi. When attempting, I get a python stacktrace and then a java crash. Everything seems to work fine when not leveraging adbapi. Not sure the on the cause, and the stack trace above `--- <exception caught here> ---` is a bit vague.. which then everything seems to get worse with the exception handling and trying to rollback. I am thinking the first thing I should establish is whether jaydebeapi  'should' be usable under twisted.enterprise.adbapi ? Any help or thoughts are greatly appreciated.

**Simple, working code example**:
```
#!/bin/env python

import jaydebeapi
conn = jaydebeapi.connect(jclassname='com.mysql.jdbc.Driver', url='jdbc:mysql://address=(protocol=tcp)(host=10.2.3.4)(port=3306)(user=coolGuy)(password=****)/test', jars='/z/test2/mysql-connector-java-5.1.45-bin.jar')
conn.close()
```

**Code with twisted**:
```
#!/bin/env python

from twisted.internet import reactor
from twisted.enterprise import adbapi
from pprint import pprint

dbpool = adbapi.ConnectionPool(
    'jaydebeapi',
    jclassname='com.mysql.jdbc.Driver',
    url='jdbc:mysql://address=(host=10.2.3.4)(port=3306)(user=coolGuy)(password=****)/test',
    jars='/z/test2/mysql-connector-java-5.1.45-bin.jar'
)

def sqlQuery():
    return dbpool.runQuery("SELECT id,state,command,time,left(replace(info,'\n','<lf>'),120) FROM information_schema.processlist ORDER BY time DESC LIMIT 50")

def printResult(l):
    if l:
        print l[0][0], "years old"
    else:
        print "No such user"

def finish():
    dbpool.close()
    reactor.stop()

d = sqlQuery()
d.addCallback(printResult)

reactor.callLater(1, finish)
reactor.run()
```

**Output from twisted code**:
```
Rollback failed
Traceback (most recent call last):
  File "/opt/lib/python2.7/site-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/opt/lib/python2.7/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/opt/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 452, in _runInteraction
    conn.rollback()
  File "/opt/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 49, in rollback
    self._connection.rollback()
  File "/z/test2/jaydebeapi/__init__.py", line 419, in rollback
    _handle_sql_exception()
  File "/z/test2/jaydebeapi/__init__.py", line 156, in _handle_sql_exception_jpype
    reraise(exc_type, exc_info[1], exc_info[2])
  File "/z/test2/jaydebeapi/__init__.py", line 417, in rollback
    self.jconn.rollback()
jaydebeapi.DatabaseError: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Can't call rollback when autocommit=true

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fbad1e1e7b9, pid=11701, tid=0x00007fbada966740
#
# JRE version: OpenJDK Runtime Environment (8.0_131-b12) (build 1.8.0_131-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.131-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [_jpype.so+0x2e7b9]  JPJavaEnv::NewLocalRef(_jobject*)+0x9
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /z/test2/hs_err_pid11701.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted
```

**Comment by claytondaley** [comment]
As you can see, the issue is that `autocommit=True` which seems to be the default for `jaydebapi`.  Try to find a place to add

```
    conn.jconn.setAutoCommit(False)
```
