### ISSUE TITLE
Cannot connect via 2 different drivers at the same time

### ISSUE THREAD

**Issue by roedelk** [baztian/jaydebeapi#90]
Hi there, 

having this short code, everything works fine:
`import jaydebeapi`
`'''`
`conn0 = jaydebeapi.connect('org.postgresql.Driver',`
`                           ['jdbc:postgresql://localhost:5432/metadb','postgres','pwd'],`
`                           '../../resources/drivers/postgresql-42.1.3.jar')`
`'''`
`conn1 = jaydebeapi.connect('com.microsoft.sqlserver.jdbc.SQLServerDriver',`
`                           ['jdbc:sqlserver://localhost:1433;databaseName=AdventureWorksDW2014',`
`                           'sa','Str0ngPassword!'], '../../resources/drivers/sqljdbc42.jar')`
`curs = conn1.cursor()`
`curs.execute('SELECT TOP 1 * FROM dbo.vDMPrep')`
`rs = curs.fetchall()`
`print(rs[0])`

The connection to MSSQL is successful as the output shows: 
>"C:\Program Files\Python37\python.exe" ../code/modules/test.py
>('Bikes', 'Road-150', 16616, 'Pacific', 33, 'High', 2011, 2010, 1, 'SO43746', 1, 1, 3578.27)
>Process finished with exit code 0 

But after adding the connection to Postgres (by removing the comment), Postgres works fine but MSSQL doesn't anymore: 

> 
>"C:\Program Files\Python37\python.exe" ../code/modules/test.py
>Traceback (most recent call last):
>  File "../code/modules/test.py", line 10, in <module>
>    '../../resources/drivers/sqljdbc42.jar')
>  File "C:\Program Files\Python37\lib\site-packages\jaydebeapi\__init__.py", line 68, in connect
>    connection = gateway.jvm.DriverManager.getConnection(*driver_args)
>  File "C:\Program Files\Python37\lib\site-packages\py4j\java_gateway.py", line 1257, in __call__
>    answer, self.gateway_client, self.target_id, self.name)
>  File "C:\Program Files\Python37\lib\site-packages\py4j\protocol.py", line 328, in get_return_value
>    format(target_id, ".", name), value)
>py4j.protocol.Py4JJavaError: An error occurred while calling z:java.sql.DriverManager.getConnection.
>: java.sql.SQLException: No suitable driver found for jdbc:sqlserver://localhost:1433;databaseName=AdventureWorksDW2014
>	at java.sql.DriverManager.getConnection(Unknown Source)
>	at java.sql.DriverManager.getConnection(Unknown Source)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>	at java.lang.reflect.Method.invoke(Unknown Source)
>	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
>	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
>	at py4j.Gateway.invoke(Gateway.java:282)
>	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
>	at py4j.commands.CallCommand.execute(CallCommand.java:79)
>	at py4j.GatewayConnection.run(GatewayConnection.java:238)
>	at java.lang.Thread.run(Unknown Source)
>Process finished with exit code 1

I assume this is a general issue on managing 2 different JDBC drivers. 2 parallel connections to 2 different Postgres connections work perfectly fine, but with Exasol I experienced the same problem.

Similar to this issue: [https://github.com/baztian/jaydebeapi/issues/56](url)
Is there really no other way than by subprocess.call?

Cheers Kolja

**Comment by roedelk** [comment]
Hi again,

I've found a solution: The parameter for the driver jar also accepts a list of drivers (and is optional). 
So I just provide all drivers at the first connection and no driver files for further connections.
Although this assumes, that you either know which one will be the first connection (as in my case for the meta database) or you can check if there is already one connection.

With this code I create a list of driver file names and provide this list instead of a driver filename:
`drivers = []`
`        for (path, dirs, files) in os.walk('../../resources/drivers/'):`
`            drivers = [path + name for name in files] `

I came to that option when reading the [ini file](https://github.com/baztian/jaydebeapi/blob/master/jaydebeapi/__init__.py), in particular the comment on the connect method (line 350).
> jars: Jar filename or sequence of filenames for the JDBC driver

Cheers Kolja
